//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concierge_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Concierge_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///        &lt;link href=&quot;css/main.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;title&gt;Recent Patient Information&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;h1&gt;Recent Patient Information&lt;/h1&gt;
        ///        &lt;h1&gt;Joseph Mulvehill MD&lt;/h1&gt;
        ///        &lt;h1&gt;Cell:917-855-0135&lt;/h1&gt;
        ///        &lt;h1&gt;Park Avenue Concierge&lt;/h1&gt;
        ///        &lt;h5&gt;10 East 78th Street Suite 1B&lt;/h5&gt;
        ///        &lt;h5&gt;New York, NY 10075&lt;/h5&gt;
        ///        &lt;h5&gt;Voice: 212-737-3136 Fax: 212-7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///        &lt;link href=&quot;css/main.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///		&lt;title&gt;Recent Patient Information&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;h1&gt;Recent Patient Information&lt;/h1&gt;
        ///        &lt;h1&gt;Joseph Mulvehill MD&lt;/h1&gt;
        ///        &lt;h1&gt;Cell:917-855-0135&lt;/h1&gt;
        ///        &lt;h1&gt;Park Avenue Concierge&lt;/h1&gt;
        ///        &lt;h5&gt;10 East 78th Street Suite 1B&lt;/h5&gt;
        ///        &lt;h5&gt;New York, NY 10075&lt;/h5&gt;
        ///        &lt;h5&gt;Voice: 212-737-3136 Fax: 212-7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string full_htm {
            get {
                return ResourceManager.GetString("full_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body 
        ///{
        ///    background-color : Black;
        ///    color : White;
        ///    font-family : Sans-Serif;
        ///}
        ///
        ///h1,h2
        ///{
        ///    text-align : center;
        ///}
        ///.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body 
        ///{
        ///    background-color : Black;
        ///    color : White;
        ///    font-family : Sans-Serif;
        ///}
        ///
        ///h1,h2
        ///{
        ///    text-align : center;
        ///}
        ///.
        /// </summary>
        internal static string index_css {
            get {
                return ResourceManager.GetString("index_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;index.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;title&gt;Welcome&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Welcome to Park Avenue Concierge Medicine&lt;/h1&gt;
        ///&lt;h2&gt;If you have trouble reading these pages, click &lt;a href=&quot;concierge/fallback.htm&quot;&gt;here.&lt;/a&gt; Otherwise, click &lt;a href=&quot;concierge/main.htm&quot;&gt;here.&lt;/a&gt;&lt;/h2&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index_htm {
            get {
                return ResourceManager.GetString("index_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;index.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;title&gt;Welcome&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Welcome to Park Avenue Concierge Medicine&lt;/h1&gt;
        ///&lt;h2&gt;If you have trouble reading these pages, click &lt;a href=&quot;concierge/fallback.htm&quot;&gt;here.&lt;/a&gt; Otherwise, click &lt;a href=&quot;concierge/main.htm&quot;&gt;here.&lt;/a&gt;&lt;/h2&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index1 {
            get {
                return ResourceManager.GetString("index1", resourceCulture);
            }
        }
        
        internal static byte[] library_zip {
            get {
                object obj = ResourceManager.GetObject("library_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///    background-color : Black;
        ///    font-family : Sans-Serif;
        ///    color : White;
        ///}
        ///
        ///body&gt;div
        ///{
        ///    width:960px;
        ///    margin-left:auto;
        ///    margin-right:auto;
        ///}
        ///
        ///body&gt;div&gt;div h5
        ///{
        ///    background-color: #222222;
        ///}
        ///
        ///body&gt;div&gt;div
        ///{
        ///    border-width : 1px;
        ///    border-color : Blue;
        ///    border-style:solid;
        ///    margin: 15px;
        ///}
        ///
        ///div.row
        ///{
        ///    width:100px;
        ///}
        ///
        ///div.even
        ///{
        ///    background-color: Black;   
        ///}
        ///div.odd
        ///{
        ///    background-color: #111111
        ///}
        ///div.summary div span.value
        ///{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///    background-color : Black;
        ///    font-family : Sans-Serif;
        ///    color : White;
        ///}
        ///
        ///body&gt;div
        ///{
        ///    width:960px;
        ///    margin-left:auto;
        ///    margin-right:auto;
        ///}
        ///
        ///body&gt;div&gt;div h5
        ///{
        ///    background-color: #222222;
        ///}
        ///
        ///body&gt;div&gt;div
        ///{
        ///    border-width : 1px;
        ///    border-color : Blue;
        ///    border-style:solid;
        ///    margin: 15px;
        ///}
        ///
        ///div.row
        ///{
        ///    width:100px;
        ///}
        ///
        ///div.even
        ///{
        ///    background-color: Black;   
        ///}
        ///div.odd
        ///{
        ///    background-color: #111111
        ///}
        ///div.summary div span.value
        ///{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main_css {
            get {
                return ResourceManager.GetString("main_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///    &lt;!--
        ///        &lt;link href=&quot;css/main.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;link href=&apos;css/jqueryui.css&apos; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/jquery.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/jqueryui.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/datatables.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/main.js&quot;&gt;&lt;/scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main_htm {
            get {
                return ResourceManager.GetString("main_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///    &lt;!--
        ///        &lt;link href=&quot;css/main.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;link href=&apos;css/jqueryui.css&apos; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/jquery.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/jqueryui.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/datatables.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;js/main.js&quot;&gt;&lt;/scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main1 {
            get {
                return ResourceManager.GetString("main1", resourceCulture);
            }
        }
    }
}
